// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Administrator, AdministratorTableId } from "./tables/Administrator.sol";
import { Config, ConfigTableId } from "./tables/Config.sol";
import { Project, ProjectData, ProjectTableId } from "./tables/Project.sol";
import { ProjectInfo, ProjectInfoData, ProjectInfoTableId } from "./tables/ProjectInfo.sol";
import { ProjectDonator, ProjectDonatorData, ProjectDonatorTableId } from "./tables/ProjectDonator.sol";
import { Donator, DonatorTableId } from "./tables/Donator.sol";
