// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ProjectData, ProjectInfoData } from "./../Tables.sol";

interface IViewSystem {
  function getMaxProjectId() external view returns (bytes32);

  function getAdministrator() external view returns (address);

  function getProject(bytes32 _projectId) external view returns (ProjectData memory);

  function getProjectInfo(bytes32 _projectId) external view returns (ProjectInfoData memory);

  function getProjectAchievedTarget(bytes32 _projectId) external view returns (bool);

  function getProjectIsBeforeDeadline(bytes32 _projectId) external view returns (bool);

  function getProjectIsBeforeWithdrawDeadline(bytes32 _projectId) external view returns (bool);

  function getProjectDonator(bytes32 _projectId) external view returns (uint256[] memory, address[] memory);
}
