// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { IAdministratorSystem } from "./IAdministratorSystem.sol";
import { IProjectSystem } from "./IProjectSystem.sol";
import { ITokenSystem } from "./ITokenSystem.sol";
import { IViewSystem } from "./IViewSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is IBaseWorld, IAdministratorSystem, IProjectSystem, ITokenSystem, IViewSystem {

}
